package se.budohoor.economics.pos2books.plugins.books.economic;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.3.0.6276

public class EconomicWebServiceSoap12Client
{
  public static void main(String [] args)
  {
    EconomicWebService economicWebService = new EconomicWebService();
    EconomicWebServiceSoap economicWebServiceSoap = economicWebService.getEconomicWebServiceSoap12();
    // Add your code to call the desired methods.
  }
}
