
package se.budohoor.economics.pos2books.plugins.books.economic;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EconomicWebService", targetNamespace = "http://e-conomic.com", wsdlLocation = "https://api.e-conomic.com/secure/api1/EconomicWebService.asmx/#%7Bhttp%3A%2F%2Fe-conomic.com%7DEconomicWebService?wsdl")
public class EconomicWebService
    extends Service
{

    private final static URL ECONOMICWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(se.budohoor.economics.pos2books.plugins.books.economic.EconomicWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = se.budohoor.economics.pos2books.plugins.books.economic.EconomicWebService.class.getResource(".");
            url = new URL(baseUrl, "https://api.e-conomic.com/secure/api1/EconomicWebService.asmx/#%7Bhttp%3A%2F%2Fe-conomic.com%7DEconomicWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://api.e-conomic.com/secure/api1/EconomicWebService.asmx/#%7Bhttp%3A%2F%2Fe-conomic.com%7DEconomicWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ECONOMICWEBSERVICE_WSDL_LOCATION = url;
    }

    public EconomicWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EconomicWebService() {
        super(ECONOMICWEBSERVICE_WSDL_LOCATION, new QName("http://e-conomic.com", "EconomicWebService"));
    }

    /**
     * 
     * @return
     *     returns EconomicWebServiceSoap
     */
    @WebEndpoint(name = "EconomicWebServiceSoap")
    public EconomicWebServiceSoap getEconomicWebServiceSoap() {
        return super.getPort(new QName("http://e-conomic.com", "EconomicWebServiceSoap"), EconomicWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EconomicWebServiceSoap
     */
    @WebEndpoint(name = "EconomicWebServiceSoap")
    public EconomicWebServiceSoap getEconomicWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://e-conomic.com", "EconomicWebServiceSoap"), EconomicWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns EconomicWebServiceSoap
     */
    @WebEndpoint(name = "EconomicWebServiceSoap12")
    public EconomicWebServiceSoap getEconomicWebServiceSoap12() {
        return super.getPort(new QName("http://e-conomic.com", "EconomicWebServiceSoap12"), EconomicWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EconomicWebServiceSoap
     */
    @WebEndpoint(name = "EconomicWebServiceSoap12")
    public EconomicWebServiceSoap getEconomicWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://e-conomic.com", "EconomicWebServiceSoap12"), EconomicWebServiceSoap.class, features);
    }

}
